
import math
import sys
import os

# Add src to path
sys.path.append(os.path.join(os.path.dirname(__file__), 'src'))

from pushing_medium.core import (
    unified_flow_field, 
    G, c, e, epsilon_0, m_e, mu_0
)

# Estimate A_M from GR
A_M_GR = G / (c * c)

def print_header(title):
    print("\n" + "="*60)
    print(f" {title}")
    print("="*60)

def z_pinch_demo():
    print_header("PM Z-Pinch Analysis")
    
    print("In PM, Z-pinch forces arise from the interaction term:")
    print("   F_pinch ~ v x (curl u)")
    print("where u is the flow field generated by the current itself.")
    
    # Configuration
    # Long cylinder of flowing material (radius R)
    R = 1.0 # meters
    velocity = 0.5 * c # Relativistic jet
    
    # 1. Gravitational Z-Pinch (Mass Current)
    # Density of a neutron star material to make it visible?
    rho_M = 1e17 # kg/m^3 (Nuclear density)
    
    # Total mass current I_M = rho * Area * v
    Area = math.pi * R**2
    I_M = rho_M * Area * velocity
    
    # Flow field at surface (approximate as line current for R outside)
    r_obs = R + 1e-3
    dist = r_obs
    
    # u_G ~ - A_M * I_M * ln(r) ... wait, for infinite wire u ~ ln(r) is potential
    # Actually u behaves like Vector Potential A.
    # For infinite wire, B ~ I/r, so u ~ ln r?
    # No, let's use the field directly. 
    # Curl u = B_G. 
    # B_G magnitude ~ A_M * u0 * I_M / (2 pi r) ? No mu0.
    # Analogue to Ampere's law:
    # curl B = mu0 J  --> curl (curl u) = -nabla^2 u = A_M J
    # Integral (curl u) . dl = A_M * I_enclosed
    # B_G * 2 pi r = A_M * I_M
    # B_G = A_M * I_M / (2 * pi * r)
    
    B_G = A_M_GR * I_M / (2 * math.pi * r_obs)
    
    # Force per unit mass: F = v x B_G
    F_m = velocity * B_G
    
    print(f"\n--- Gravitational Z-Pinch (Astrophysical Jet) ---")
    print(f"Density: {rho_M:.1e} kg/m^3")
    print(f"Velocity: {velocity/c:.1f} c")
    print(f"Mass Current I_M: {I_M:.2e} kg/s")
    print(f"Gravitomagnetic Field B_G: {B_G:.2e} 1/s")
    print(f"Pinch Acceleration (Lorentz-like): {F_m:.2e} m/s^2")
    
    # Compare to static Newtonian repulsion/attraction?
    # Static gravity pulls inward (a_G). 
    # a_G = G * M_enclosed / r^2
    # M_enclosed (per unit length?) No, sphere.
    # For infinite cylinder, g = 2 G lambda / r
    linear_mass_density = rho_M * Area
    a_G_static = 2 * G * linear_mass_density / r_obs
    
    print(f"Static Gravity inward accel:       {a_G_static:.2e} m/s^2")
    print(f"Ratio (Dynamic Pinch / Static):    {F_m / a_G_static:.4f}")
    
    print("\nResult: The Pinch effect scales as v^2/c^2.")
    print(f"v/c = {velocity/c:.1f} -> ratio should be approx (v/c)^2?")
    expected_ratio = (velocity/c)**2
    print(f"Expected (v/c)^2:                  {expected_ratio:.4f}")
    
    print("\nConclusion: Gravitational Z-pinch exists in PM (and GR) but is")
    print("only explicitly visible as a relativistic correction to static attraction.")
    print("Parallel mass currents attract MORE than static masses.")

    # 2. Electromagnetic Z-Pinch
    print(f"\n--- Electromagnetic Z-Pinch (Standard Plasma) ---")
    # Current I
    I_q = 1e6 # Amps
    
    # PM formulation: B_q = A_q * I_q / (2 pi r) ?
    # Wait, we need to recover B_standard = mu0 I / (2 pi r)
    # PM Force = v x (curl u). 
    # In standard EM: F/m = (q/m) v x B
    # PM unifies this by scaling u.
    # u_q should map to (q/m) A_potential ? No.
    # The PM geodesic equation is geometric.
    # It doesn't have q/m in the acceleration term unless it's implicit in the coupling.
    
    print("Analysis:")
    print("Unlike gravity (where mass cancels out F=ma), EM forces depend on q/m.")
    print("The PM metric formalism is mass-independent (geometric).")
    print("Therefore, standard EM Z-pinch cannot be PURELY geometric frame dragging")
    print("unless the localized 'metric' felt by the particle depends on its charge-to-mass ratio.")
    print("This confirms PM's 'Force = Geometric' view requires species-dependent refractive indices.")
    
if __name__ == "__main__":
    z_pinch_demo()
